#pragma once

#define MEMENTO_DEVICE_TYPE 0x8200

#define DECLARE_MEMENTO_IOCTL(Function) CTL_CODE(MEMENTO_DEVICE_TYPE, Function, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define GET_MODULE_BASE_IOCTL DECLARE_MEMENTO_IOCTL(0x801)
#define READ_PROCESS_MEMORY DECLARE_MEMENTO_IOCTL(0x802)
#define WRITE_PROCESS_MEMORY DECLARE_MEMENTO_IOCTL(0x803)